### ISSUE TITLE
Kadane's Algorithm

### ISSUE THREAD

**Issue by mugiwara798** [mugiwara798/The_Algo_Directory#1]
Please explain the Kadane's Algorithm along with a suitable example. You can also add links of the questions related to it.

**Comment by AshwinSriram11** [comment]
Can I work on this issue? @mugiwara798

**Comment by mugiwara798** [comment]
Go for it @AshwinSriram11

**Comment by AshwinSriram11** [comment]
I have raised a PR @mugiwara798 .Kindly check it.
